### ISSUE TITLE
Rethink edit and delete buttons

### ISSUE THREAD

**Issue by doomspork** [doomspork/elixir-companies#469]
The buttons are currently too big and take up too much valuable real estate on each card.  How can we improve the UX while retaining the functionality?

![image](https://user-images.githubusercontent.com/73386/53703154-d3a56c80-3dcb-11e9-88a1-7c82d69170ac.png)

**Comment by doomspork** [comment]
@burden / @tajchumber as the resident UX experts any thoughts?

**Comment by tajchumber** [comment]
### Solution 1

Remove the text and leave the icons only, we would have to add `title` tags to the `a` elements so that some text would show on hover.

### solution 2

Move the edit and delete icons in a dropdown menu on the top right of the card see rough sketches below:
![1](https://user-images.githubusercontent.com/16062635/53703470-53eac280-3e0a-11e9-8f2a-16fd77886d7a.jpg)

![2](https://user-images.githubusercontent.com/16062635/53703471-56e5b300-3e0a-11e9-83b4-58312d586e36.jpg)

**Comment by doomspork** [comment]
Solution 2 gets my vote. @gemantzu / @burden?

**Comment by doomspork** [comment]
This is also an issue for jobs: 
![image](https://user-images.githubusercontent.com/73386/53704298-cb076300-3dd8-11e9-9466-94e62b4f497f.png)

**Comment by doomspork** [comment]
Should the edit company page also allow you to manage jobs to avoid those individual controls?

What do you think of making cards bigger?  1 card == 2 existing cards. It would make more space for the description.

**Comment by gemantzu** [comment]
I think the second solution is better, and we could take a similar approach on the jobs. Regarding making them bigger, probably a 3 per page solution would make more sense, making them twice as big might be too much.

**Comment by tajchumber** [comment]
option 2 it is!

I shall open a PR for this this weekend!
